name: Test

on: [push]

env:
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up en_US locale
        run: |
          sudo locale-gen "en_US.UTF-8"
          sudo update-locale "LANG=en_US.UTF-8"
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Install pylint
        run: pip3 install pylint
      - name: Run pylint
        run: pylint **/*.py
      - name: Run tests
        run: bash test.sh
  
  windows:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build
      - name: Build
        run: python -m build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: dist
  
  macos:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build
      - name: Build
        run: python -m build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: MacOS
          path: dist

  linux:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install build
      - name: Build
        run: python3 -m build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: dist

