name: Test

on: [push]

env:
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up en_US locale
        run: |
          sudo locale-gen "en_US.UTF-8"
          sudo update-locale "LANG=en_US.UTF-8"
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Install pylint
        run: pip3 install pylint
      - name: Run pylint
        run: pylint **/*.py
      - name: Run tests
        run: bash test.sh

  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install build
      - name: Build
        run: python3 -m build
      - name: Generate changelog
        run: git log $(git describe --abbrev=0 --tags)..HEAD --oneline --pretty="- %s" > CHANGELOG.md
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files:
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

