name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up en_US locale
        run: |
          sudo locale-gen --purge "en_US.UTF-8"
          sudo update-locale "LANG=en_US.UTF-8"
          export LANG=en_US.UTF-8
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Install pylint
        run: pip3 install pylint
      - name: Run pylint
        run: pylint **/*.py
      - name: Run tests
        run: bash test.sh
